name: Build package

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    uses: md2it/browser-extension-ci-cd/.github/workflows/build-extension.yml@v1.4.2
    with:
      extension-root: extension
      zip-name: element-deleter.zip
      artifact-name: element-deleter-build
